name: main branch CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/wf-deploy.yml
    secrets: inherit
